### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np

In [2]:
a = np.zeros((2, 3))
b = np.empty((2, 3))
print(a)
print(b)
%timeit a
%timeit b

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
43.5 ns ± 1.24 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
42.1 ns ± 3.72 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


np.zeros() 可建立一數值皆為0且指定形狀的矩陣。

np.empty() 不會給予特定數值，建立一個指定狀的矩陣。此外，在處理大量資料時使用此方法可節省時間。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [3]:
from numpy.random import default_rng

rng=default_rng()
a=rng.random((2,3)) * 100

print(a)
print(a.round())
print(np.round(a))

[[61.96530277 11.90994197 57.54628778]
 [ 2.63318551 94.81934894 29.35026793]]
[[62. 12. 58.]
 [ 3. 95. 29.]]
[[62. 12. 58.]
 [ 3. 95. 29.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [4]:
m=20
n=40

a=rng.random((2,3))*(n-m)
b=a

print((a-b%1)+m)

[[26. 24. 27.]
 [25. 23. 36.]]
