### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(3, 2)
print(a.sum())
print(np.sum(a))
print(sum(a))

15
15
[6 9]


a.sum() 及 np.sum(a) 為 NumPy 專屬的函式，且輸出結果相同。

sum(a) 則為 Python 通用的函式，且其預設是從 axis = 0 的方向做加總，得到一個一維的矩陣。

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [3]:
#資料的正規化(Normalization)是將原始資料的數據按比例縮放於 [0, 1] 區間中，且不改變其原本分佈。
A = np.random.random((5, 5))
print(A)

A_normalization = (A - A.min()) / (A.max() - A.min())
print("After normalization:")
print(A_normalization)

[[0.33867939 0.49410121 0.84117986 0.0194312  0.72443534]
 [0.5807096  0.99326321 0.34395425 0.88430503 0.40532   ]
 [0.06936468 0.52098804 0.95380905 0.72546303 0.86229962]
 [0.89197033 0.88235291 0.04373    0.00409721 0.67484148]
 [0.25800801 0.32768086 0.99334461 0.21378697 0.98653762]]
After normalization:
[[0.33821892 0.49533008 0.8461813  0.01550066 0.72816783]
 [0.58287986 0.99991772 0.34355111 0.88977522 0.40558387]
 [0.06597689 0.52250916 0.96003471 0.72920669 0.86753062]
 [0.89752384 0.88780188 0.04006358 0.         0.6780349 ]
 [0.25667068 0.32710083 1.         0.21196897 0.99311902]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [4]:
arr = np.random.random(10)
arr[np.argmax(arr)] = -1
print(arr)

[ 0.64424076  0.84298094  0.07971636 -1.          0.17451717  0.20890902
  0.44170981  0.01190227  0.10480151  0.57678508]
